### ISSUE TITLE
Git Cheetah causes explorer to crash when ".git/packed-refs" file is long enough

### ISSUE THREAD

**Issue by jakub-g** [msysgit/Git-Cheetah#19]
win7, git bash 1.9.5 (was happening for many weeks for me at least since 1.9.4)

I've started noticing that one of my repos is causing crashes / unresponsiveness / extremely long processing time (~40seconds) in windows explorer (Windows 7) when I **right click the folder, or inside the folder** (on some file or blank space).

This was happening only for a certain git repo and not the others.

I investigated and it seems the issue is the contents of certain files in `.git` folder.

Here's a script with a minimum working example in Windows 7 (tested on two machines):

```
#!/bin/bash
mkdir -p /d/xkiller/.git
cd /d/xkiller/.git
mkdir refs
mkdir objects
echo "ref: refs/heads/master" > HEAD
echo "# pack-refs with: peeled fully-peeled" >> packed-refs
node -e 'for(var i=0;i<360; i++) console.log("2aa83bb279c1f10d11fca7ee46e52869b3c4ee67 refs/heads/branch" + i) ;' >> packed-refs
```
(I was lazy and used nodejs to create packed-refs file)

* run the script to create `D:/xkiller` folder.
* then, open `D:` in windows explorer
* right click `xkiller`. It should hang your explorer window for 40+ seconds

It seem the issue at least partially is the length of `packed-refs` file, but I'm not sure if this is the only one **(when I decrease file to be <250 lines the problem - in this particular scenario at least - goes away)**. It's pretty hard and time consuming to black-box-debug it :)

Can you please check if you can reproduce the issue?

**Comment by dscho** [comment]
I tried to find time to tackle this issue, but sadly I failed, and realistically I have to admit that I am too busy with too many other things. Sorry!

If you want to investigate further, I would suggest to rebuild with debugging enabled (`make DEBUG=1`) and to have a look at the log file (it should be located in [`<user-home>\AppData\Local\Temp\git_shell_ext_debug.txt`](https://github.com/msysgit/Git-Cheetah/blob/122064e882cd17ce76198638f4011e251f0f1c90/common/debug.c#L24-L27). This log file should give you an idea which tasks take such a long time, so that you can then performance-profile these tasks from the command-line.

Again, sorry to kick the ball back into your court!
