### ISSUE TITLE
Context menu modifications

### ISSUE THREAD

**Issue by Efreak** [msysgit/Git-Cheetah#21]
Some git settings for the following would be nice. Regarding the discussion in #20, the settings don't need to be located in `%appdata%`, you can just as easily store them in a `c:\program files (x86)\Git\config.ini` or some such, or in `git config` settings in `$HOME/.gitconfig`, or in a registry entry (there should be *some* way to abstract between gconf and the registry...)

- Only show git items when the repo already exists; if .git doesn't exist, don't show anything.
- Show options for both powershell *and* git bash
- #20 
- Probably far more windows-specific, it would be nice to have an overlays a la dropbox/skydrive/etc to show the status of files in a git repo (Icon Overlay Handler) or some other form of identifying the status of a file *in explorer* without first opening git. Even just setting the file metadata that's shown in the details/preview pane would be useful.

~~I started to check out whether or not the patch linked in #20 still works, however [I am unable to install msysgit](http://i.imgur.com/LdxNH5l.png). One would think this is related to the fact that the installer places sh.exe in `c:\msysgit\install_tmp`, but copying the contents of `c:\msysgit\install_tmp` to `c:\msysgit` and rerunning the netinstall doesn't help. The netinstall is the *"easiest"* way to install msysgit, implying there's a less easy way, but I have no idea what the less easy way is, as it's not mentioned anywhere.~~ Git for Windows SDK works fine, I just have to get around to trying it.

**Comment by dscho** [comment]
> the settings don't need to be located in %appdata%, you can just as easily store them in a c:\program files (x86)\Git\config.ini

I am afraid that this is not an option: for most Git for Windows users, `C:\Program Files (x86)\` is a read-only area.

> I started to check out whether or not the patch linked in #20 still works, however I am unable to install msysgit.

It would be good to open a ticket at https://github.com/msysgit/msysgit/issues/new, then, with complete information.

> The netinstall is the "easiest" way to install msysgit, implying there's a less easy way, but I have no idea what the less easy way is, as it's not mentioned anywhere.

Why, the less easy way is to follow the steps of https://github.com/msysgit/msysgit/blob/master/share/msysGit/net/setup-msysgit.sh manually (but mind you, a naive copy-paste won't be doing the job). In short, you could install regular Git for Windows and then clone https://github.com/msysgit/msysgit somewhere (followed by some housekeeping).

But please do note that the information about installing msysgit is now hidden in the Git Cheetah tracker, because the bug report about installing msysgit was mentioned in the wrong place. Other people will not have a chance to find it. Not so good.

**Comment by dscho** [comment]
> It would be good to open a ticket at https://github.com/msysgit/msysgit/issues/new, then, with complete information.

Correction: it would now be good to [open a ticket in Git for Windows 2.x](http://git-for-windows.github.io/#contribute).

**Comment by kusma** [comment]
> - Only show git items when the repo already exists;if .git doesn't exist, don't show anything.

That would make the "Git Init Here"-option moot. Please don't.

**Comment by Efreak** [comment]
That would be why I'm asking for the *option* to have this. I realize that some people appreciate it, otherwise it wouldn't be there. However, I usually init my repos here on github, which makes this rather useless. Again, all I'm looking to do is clean up my context menus; it's annoying enough that Microsoft decided we don't need to edit entries in them after XP.

>Correction: it would now be good to open a ticket in Git for Windows 2.x.

I checked out the Git for Windows SDK, and it works fine. Should I leave this issue here, or move it to git for windows? I'm not entirely sure of the new setup.

**Comment by kusma** [comment]
@Efreak: Different people have different work-flows. I usually init my repos locally first. I only ever push code anywhere if it turns out to be interesting. So no, not at all useless.

**Comment by dscho** [comment]
> I checked out the Git for Windows SDK, and it works fine. Should I leave this issue here, or move it to git for windows? I'm not entirely sure of the new setup.

My suggestion went for woes with setting up the development environment. Since that works, no, there is no need to open a new ticket.

As to your suggestions, I think they are pretty sound so far. Why don't you go and implement them? We can always fiddle with existing patches, e.g. to ensure that `Git Init Here` is shown *only* when there is no `.git/` subdirectory in that folder (because I do agree with @kusma)... But better discuss that on top of working code.

**Comment by dscho** [comment]
@Efreak did you manage to clone https://github.com/msysgit/Git-Cheetah/ inside a [Git SDK](http://git-for-windows.github.io/#download-sdk) and to build it?
